[package]
name = "leaf-examples"
description = "Examples for the Machine Learning Framework 'Leaf'"
version = "0.1.0"
authors = ["Bernhard Schuster <bernhard@ratpoison.io>",
           "Michael Hirn <mj@autumnai.com>",
           "Maximilian Goisser <max@autumnai.com>"]

[dependencies]
# cuticula = { path = "../cuticula", default-features = false }
leaf = { path = "../leaf", default-features = false, version = "0.2.2" }
coaster = { path = "../coaster", default-features = false, version = "0.1.0" }

csv = "0.14"
hyper = "0.6"

log = "0.3.7"
env_logger = "0.4.2"
timeit = "0.1.2"

# CLI tooling
docopt = "0.6.75"
rustc-serialize = "0.3"

clippy = { version = "0.0.23", optional = true }


[features]
default = ["native", "opencl", "cuda"]
native = ["leaf/native", "coaster/native"]
opencl = ["leaf/opencl", "coaster/opencl"]
cuda = ["leaf/cuda", "coaster/cuda"]

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 2
