[package]
name            = "coaster-blas"
description     = "Coaster library for full BLAS support"
version         = "0.2.0"
authors         = ["Bernhard Schuster <bernhard@ratpoison.io>",
		   "Michael Hirn <mj@autumnai.com>",
                   "Maximilian Goisser <max@autumnai.com>"]

repository      = "https://github.com/ratpoison-io/coaster-blas"
homepage        = "https://ratpoison.io/coaster-blas"
documentation   = "https://autumnai.github.io/coaster-blas"
readme          = "README.md"

keywords        = ["blas", "coaster", "computation", "hpc", "plugin"]
license         = "MIT OR Apache-2.0"

[dependencies]
coaster = "0.1.0"
lazy_static = "0.1"

# native
rblas = { path = "../rust-blas", version = "0.0.13", optional = true }

# cuda
rcublas = { path = "../rust-cublas/cublas", version = "0.2.0",  optional = true }

clippy = { version = "0.0.27", optional = true }

[dev-dependencies]

rand = "0.3"

[features]
default = ["native", "cuda", "opencl"]
native = ["coaster/native", "rblas"]
cuda = ["coaster/cuda", "rcublas"]
opencl = ["coaster/opencl"]

travis = ["native"]
dev = []
lint = ["clippy"]
