[package]
name = "leaf-examples"
description = "Examples for the Machine Learning Framework 'Leaf'"
version = "0.1.0"
authors = ["Michael Hirn <mj@autumnai.com>"]

[dependencies]
csv = "0.14"
cuticula = "0.1.4"
hyper = "0.6"
# CLI tooling
docopt = "0.6.75"
docopt_macros = "0.6.75"
rustc-serialize = "0.3"
