[package]
name = "cuticula"
description = "Data Transformation library for Machine Learning"
authors = ["Michael Hirn <mj@autumnai.com>"]
version = "0.1.0"
readme = "README.md"
keywords = ["transformation", "encoding", "machine learning", "non-numeric"]

[dependencies]
image = "0.4.0"
murmurhash3 = "0.0.5"
modifier = "*"
clippy = "*"
