[package]
name = "leaf"
description = "Machine Learning Framework"
version = "0.0.1"
authors = [
  "Maximilian Goisser <max@autumnai.com>",
  "Michael Hirn <mj@autumnai.com>"
]
repository = "https://github.com/autumnai/leaf"
homepage = "https://github.com/autumnai/leaf"
documentation = "http://autumnai.github.io/leaf"
readme = "README.md"
keywords = ["deep-learning", "neural-networks", "machine-learning", "framework"]
license = "MIT"

[dependencies]
phloem = "0.2.2"
rblas = "0.0.9"
log = "0.3.2"
clippy = "~0.0.22"

[features]
default = []
dev = [] # possibly for clippy
